api:
  dashboard: true
  insecure: true  

entryPoints:
  web:
    address: ":80"

  websecure:
    address: ":443"

providers:
  swarm:
    endpoint: "tcp://app-proxy:2375"
    exposedByDefault: false
    network: app_proxy_web
    refreshSeconds: 15

log:
  level: "INFO"

accessLog:
  bufferingSize: 100

metrics:
  prometheus:
    addEntryPointsLabels: true
    addServicesLabels: true
    entryPoint: traefik
