#!/usr/bin/env bash

set -euo pipefail

# ── Logging ───────────────────────────────────────────────────────────────────
log() { echo "[galera] $(date '+%H:%M:%S') $*"; }
die() { log "FATAL: $*"; exit 1; }

# ── Secrets ───────────────────────────────────────────────────────────────────
ROOT_PWD_FILE="${MYSQL_ROOT_PASSWORD_FILE:-/run/secrets/db_root_password}"
SST_PWD_FILE="${GALERA_SST_PASSWORD_FILE:-/run/secrets/db_galera_password}"

[ -f "$ROOT_PWD_FILE" ] || die "Root password secret not found: $ROOT_PWD_FILE"
[ -f "$SST_PWD_FILE"  ] || die "SST password secret not found: $SST_PWD_FILE"

SST_PASSWORD=$(< "$SST_PWD_FILE")


# ── Node Identity ─────────────────────────────────────────────────────────────
NODE_NAME="${GALERA_NODE_NAME:-$(hostname)}"

NODE_ADDRESS="${GALERA_NODE_ADDRESS:-$(hostname -i 2>/dev/null | awk '{print $1}')}"
log "Node identity → name=${NODE_NAME}  overlay_addr=${NODE_ADDRESS}"

# ── Cluster Parameters ────────────────────────────────────────────────────────
CLUSTER_NAME="${GALERA_CLUSTER_NAME:-galera_cluster}"
CLUSTER_ADDRESS="${GALERA_CLUSTER_ADDRESS:-gcomm://app_db}"
CLUSTER_SERVICE="${GALERA_CLUSTER_SERVICE:-app_db}"   # Swarm service DNS name
BOOTSTRAP_NODE="${GALERA_BOOTSTRAP_NODE:-db1}"
SST_USER="${GALERA_SST_USER:-galera_sst}"

DATADIR=/var/lib/mysql
BOOTSTRAP=false

# ── Bootstrap / Join Decision ─────────────────────────────────────────────────
log "Evaluating cluster state..."

if [ -s "${DATADIR}/grastate.dat" ]; then

    # ── Case 1 & 2: Existing data directory ──────────────────────────────────
    log "Found existing datadir with grastate.dat"
    if grep -q "safe_to_bootstrap: 1" "${DATADIR}/grastate.dat"; then
        log "safe_to_bootstrap=1 → bootstrapping cluster from this node's data"
        BOOTSTRAP=true
    else
        log "safe_to_bootstrap=0 → joining existing cluster (IST/SST will sync state)"
        BOOTSTRAP=false
    fi

elif [ -z "$(ls -A "$DATADIR" 2>/dev/null)" ]; then

    # ── Case 3 & 4: Fresh / empty data directory ──────────────────────────────
    log "Empty datadir detected — fresh deployment"

    if [ "$NODE_NAME" = "$BOOTSTRAP_NODE" ]; then
        log "I am the bootstrap node (${BOOTSTRAP_NODE}) → starting new cluster"
        BOOTSTRAP=true

    else
        log "I am NOT the bootstrap node — waiting for cluster to form..."
        BOOTSTRAP=false

        MAX_WAIT=120
        WAITED=0
        log "Probing ${CLUSTER_SERVICE}:4567 (timeout ${MAX_WAIT}s)..."

        until nc -z "$CLUSTER_SERVICE" 4567 2>/dev/null; do
            if [ "$WAITED" -ge "$MAX_WAIT" ]; then
                log "WARNING: cluster not reachable after ${MAX_WAIT}s — joining anyway (Galera will retry)"
                break
            fi
            log "  not yet reachable — retrying in 5s (${WAITED}/${MAX_WAIT}s elapsed)"
            sleep 5
            WAITED=$((WAITED + 5))
        done
        log "Cluster reachable — proceeding to join"
    fi

else

    # ── Case 5: Datadir has content but no grastate.dat ───────────────────────
    log "WARNING: datadir not empty but grastate.dat missing — joining (expect forced SST)"
    BOOTSTRAP=false

fi

# ── Write Runtime Galera Config ───────────────────────────────────────────────
RUNTIME_CNF=/etc/mysql/mariadb.conf.d/61-galera-runtime.cnf

log "Writing runtime config → ${RUNTIME_CNF}"
cat > "$RUNTIME_CNF" <<EOF
# Auto-generated by galera-entrypoint.sh on $(date -u '+%Y-%m-%dT%H:%M:%SZ')
# Do not edit — this file is overwritten on every container start.
[mysqld]
wsrep_node_name     = ${NODE_NAME}
wsrep_node_address  = ${NODE_ADDRESS}
wsrep_cluster_name  = ${CLUSTER_NAME}
wsrep_cluster_address = ${CLUSTER_ADDRESS}
wsrep_sst_auth      = ${SST_USER}:${SST_PASSWORD}
EOF

# ── Build Extra Flags ─────────────────────────────────────────────────────────
EXTRA_FLAGS=""
if [ "$BOOTSTRAP" = "true" ]; then
    EXTRA_FLAGS="--wsrep-new-cluster"
    log "Mode: BOOTSTRAP → mariadbd --wsrep-new-cluster"
else
    log "Mode: JOIN       → mariadbd (normal start)"
fi

# ── Hand Off to Official MariaDB Entrypoint ───────────────────────────────────
log "Handing off to docker-entrypoint.sh..."
exec /usr/local/bin/docker-entrypoint.sh "$@" $EXTRA_FLAGS
