services:
  horno:
    container_name: horno
    hostname: horno
    image: httpd:2.4
    ports:
      - 80:80
    volumes:
      - ./web/lugar.conf:/etc/apache2/sites-enabled/lugar.conf
      - ./web/sentadilla.lan:/opt/web/sentadilla.lan
      - ./web/ports.conf:/etc/apache2/ports.conf
      - ./web/apache2.conf:/etc/apache2/apache2.conf
    networks:
      superred:
        aliases:
          - lugarcillo.lan
    develop:
      watch:
        - path: ./web/lugar.conf
          action: restart
    deploy:
      placement:
        constraints:
          - node.labels.role == web
  soporte:
    container_name: soporte
    hostname: soporte
    image: mcr.microsoft.com/mssql/server:2025-latest
    environment:
      SA_PASSWORD: "abc123.."
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    volumes:
      - sqldata:/var/opt/mssql
    deploy:
      placement:
        constraints:
          - node.labels.role == web

  listillo:
    container_name: listillo
    hostname: listillo
    image: prom/prometheus
    ports:
      - 9090:9090
    volumes:
      - ./prometheus/data/:/prometheus
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    deploy:
      placement:
        constraints:
          - node.labels.role == web
volumes:
  sqldata:

networks:
  superred:
    ipam:
      config:
        - subnet: 192.168.50.0/24
